### ISSUE TITLE
Unknown error when adding Button Panel [duplicate_device]

### ISSUE THREAD

**Issue by TsiisSkaaf** [AdyRock/com.ady.button_plus#72] opened 2024-01-02 20:53 UTC
**Homey**
- Model: 2019 or 2023
- Firmware Version: 10.0.3
- App Version: Test 0.2.12

**Describe the bug**
1. I removed the device from Homey.
2. Reset my Button+, to load my own config.
3. Later on I decided to try the Homey-app again.
4. After pressing connect there is short (1 second) a succes-message before the message: "Error: Er is een onbekende fout opgetreden [duplicate_device]" show up

What I tryed:
1. Reset my Button+ to factory defaults (again)
2. Connected MQTT Explorer to mqtt (button+ on homey)
3. Deleted topics
4. Removed Button+ app from homey
6. Re-installed Button+ test 0.2.12
7. Add new device to homey
8. Same error message

**Comment by AdyRock** [comment] 2024-01-02 23:57
I can't reproduce that issue here. I have tried deleting the device from Homey and re-adding it, both before and after a factory reset of the Button +.

Could you look in the https://tools.developer.homey.app/tools/devices to see if there is already a device that is not being removed?

**Comment by AdyRock** [comment] 2024-01-16 21:17
Are you still having this problem?

**Comment by TsiisSkaaf** [comment] 2024-01-17 13:53
I did not try it again. It looks like it is working...

**Comment by AdyRock** [comment] 2024-01-17 14:11
Ok, I will close this off, but feel free to reopen it if you have the same problem again.

**Closed** 2024-01-17 14:11 UTC
Labels: bug
